### ISSUE TITLE
could you provide the patches needed for compiling ruby 2.0.0 in alpine linux?

### ISSUE THREAD

**Issue by gizmomogwai** [mayok/alpine-ruby#1]
the gists from your dockerfile are 404-ing now.

**Comment by mayok** [comment]
somehow, I deleted my gist.

I tried to make those again, so please wait

**Comment by gizmomogwai** [comment]
thanks a lot!

**Comment by mayok** [comment]
I created patches and update Dockerfile.

**Comment by gizmomogwai** [comment]
wow ... thank you so much .. i will give it a try immediately!
